### ISSUE TITLE
Discord application token is exposed

### ISSUE THREAD

**Issue by amalbansode** [TannerGabriel/discord-bot#1]
`config.json` contains your bot's application token. Anyone can take control of your bot, depending on where it's active. I would suggest changing the token in your developer settings, and hiding it here (perhaps replace it with a placeholder?).

**Comment by TannerGabriel** [comment]
Thank you for your comment @amalbansode. I noticed that myself some time ago and deleted the token so it couldn't be abused by people. You are also right that it is a great idea to add a placeholder instead because it can be irritating for people.

Thank you for taking the time to report this I really appreciate it

Kind regards,
Gabriel Tanner
