### ISSUE TITLE
Bot is showing as deafened 

### ISSUE THREAD

**Issue by willm132** [TannerGabriel/discord-bot#117]
Anytime the bot joins the server to play music it is showing deafened. This does not stop it from working, just annoying to see. Anyway to fix this?

![Capture](https://user-images.githubusercontent.com/47162632/134106833-5ce51c0f-8d4a-4a26-84e9-7657f973a402.PNG)

**Comment by godsyn** [comment]
in node_modules/discord-player/dist/Structures/Queue.js

...
```
        Object.assign(this.options, {
            leaveOnEnd: true,
            leaveOnStop: true,
            leaveOnEmpty: true,
            leaveOnEmptyCooldown: 1000,
            autoSelfDeaf: true,
            ytdlOptions: {
```
set 
            autoSelfDeaf: false,

**Comment by TannerGabriel** [comment]
It is not a good idea to change something in the `node_modules` directory since it won't be saved and will automatically change back when running `npm` installation commands. Maybe it would be best to add a configuration option for this to the discord-player repository (which I can do if that would help you out).

**Comment by TannerGabriel** [comment]
I just tried it out and you can add the `autoSelfDeaf: false` to the `createQueue` function in the play file. Here is how that would look:

```
const queue = await player.createQueue(interaction.guild, {
        metadata: interaction.channel,
        autoSelfDeaf: false
});
```
