### ISSUE TITLE
Finding songs

### ISSUE THREAD

**Issue by D3ord3NidAm** [TannerGabriel/discord-bot#35]
I would like the ability to search for songs by name or artist or both.
![songs](https://user-images.githubusercontent.com/34216187/87872588-78075f00-c97f-11ea-9af2-9ccd2558c9bf.png)

**Comment by TannerGabriel** [comment]
I'm not planning on implementing this functionality because it needs a Youtube API token, and I think it would overcomplicate the setup process of the bot.

This repository should be an easy example of how to create your own Discord music bot, and I think the feature would be unnecessary.

That said here are a few libraries you can use to implement the functionality yourself: 
- [Youtube search](https://www.npmjs.com/package/youtube-search)
- [YT Search](https://www.npmjs.com/package/ytsearcher)

You can use these libraries to get the URL of the song you want using the song name and then play the song by passing the URL to the ytdl-core library as you are already doing now.
