### ISSUE TITLE
YouTube live notification bot for discord

### ISSUE THREAD

**Issue by rajamoulimallareddy** [TannerGabriel/discord-bot#51]
Create a code for YouTube live notifier when someone goes live on YouTube it should automatically post it in discord in a channel please help

**Comment by TannerGabriel** [comment]
This might be possible using the [Youtube API](https://developers.google.com/youtube/v3), but I haven't tried it out myself. Also, this is not part of the discord bot since it is meant as a simple application that is easy to understand.

You can also look at this [Stackoverflow question](https://stackoverflow.com/questions/46558476/is-there-a-way-to-get-notifications-from-youtube-api-when-broadcaster-is-live), which might help you.

**Comment by SwampDolphin97** [comment]
Also, you can use trigger based applet like IFTTT or zapier if doing this is a hassle for you

**Example** 
![image](https://user-images.githubusercontent.com/27912312/101182520-33e9d200-3674-11eb-82eb-974d0d26e88e.png)

**Comment by SwampDolphin97** [comment]
Please close this issue. 
@TannerGabriel
