### ISSUE TITLE
Can't read a property correctly.

### ISSUE THREAD

**Issue by Rp317** [TannerGabriel/discord-bot#61]
**Describe the bug**
This bug happens when you run the code and do a command

**Expected behavior**
the message that appears is "TypeError: Cannot read property 'execute' of undefined."

**Desktop (please complete the following information):**
 - Chromebook
 - Google

**Comment by TannerGabriel** [comment]
I'm sorry, but I can currently not reproduce your issue. Can you provide more information like your Operating System and how you are running the application (Nodejs, Docker, ...).

**Comment by SwampDolphin97** [comment]
This error generally happens due to [this.](https://stackoverflow.com/questions/64015041/typeerror-cannot-read-property-execute-of-undefined)

However, @TannerGabriel got this done correctly at 
![screenshot_20210214_040728](https://user-images.githubusercontent.com/27912312/107863425-5d945600-6e7a-11eb-9fcf-528588fc2003.png)

**Comment by TannerGabriel** [comment]
@Rp317 Were you able to fix your issue? If so, please tell us how you did it so we can close the issue.

**Comment by Rp317** [comment]
I fixed it by getting rid of a typo i accidentally made in the code. sorry.
