### ISSUE TITLE
Music Bot Issue

### ISSUE THREAD

**Issue by Vestiary** [TannerGabriel/discord-bot#62]
[Google Translate]
when I do a command, the bot repeats the same message many times, I would like to see how it can be fixed and send only one message
![image](https://user-images.githubusercontent.com/54251440/107999203-a4429700-6fc5-11eb-8a0c-26633e0258e9.png)

**Comment by TannerGabriel** [comment]
Since you don't provide much information, I can only guess the cause. You are probably running the application using Docker and forgot to stop the container before opening another one.

You can check this using:

```bash
docker ps
```

If multiple discord bots are running just remove them using `docker rm`.

You can prevent this from happening by adding the `--rm` flag to the `docker run` command.

**Comment by heauma** [comment]
Hello I have the same problem as the person on the left is what you could explain in detail how to use the (docker ps) ?

**Comment by TannerGabriel** [comment]
It seems that you have your bot running multiple times. I concluded that you are using Docker to run the discord bot. If so, you can type the `docker ps` command into your console to see all your running containers.

If you started the discord bot using Node.js `node index.js`, you need to look in your processes and find if multiple instances are running. If that is not the issue, please provide more information like your OS, Nodejs version and details about how you deploy the application.
